vim.keymap.set("n", "<leader>w", ":w<CR>", { desc = "Save this file" })
vim.keymap.set("n", "<leader>q", ":q<CR>", { desc = "Quit" })
vim.keymap.set("i", "jk", "<Esc>")
vim.keymap.set({"n","v"}, "<leader>l", "$")
vim.keymap.set("n", "<leader>h", "^")
vim.keymap.set("n", "H", "<cmd>bprevious<cr>", { desc = "Prev Buffer" })
vim.keymap.set("n", "L", "<cmd>bnext<cr>", { desc = "Next Buffer" })
